backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
    - name: "courses"
    label: "Courses"
    folder: "content/courses"
    create: true
    slug: "{{slug}}"
    fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Description", name: "description", widget: "text"}
            - {label: "Body", name: "body", widget: "markdown"}